on:
  push:
    branches:
      - master
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    # bang.pk
    # - name: Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
    #   with:
    #     server: ftp.itlifee.net
    #     username: itlifeen@bang.pk
    #     password: pIvHFl}h_7eZ6p&r

    # akithub.space umar & jaffar ali 
    # - name: Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
    #   with:
    #     server: ftp.akithub.space
    #     username: admin@akithub.space
    #     password: z[!@cphCVZJk#07.

    # Saleem sb, HAS 
    # - name: Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
    #   with:
    #     server: ftp.itlifee.net
    #     username: hasfbr@hasfbr.itlifee.net
    #     password: yp){r[DRwoWJM?)H

     # Tariq sb, TLA 
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.bang.pk
        username: u525064917.bangpk
        password: 3Mz!1BCfbvQmLb+d1


       # sitc aqeel afridi
    # - name: Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
    #   with:
    #     server: ftp.sitccloud.space
    #     username: admin@sitccloud.space
    #     password: MOq7cm7o&V@gC3bb
